---
- name: install apache2
  become: yes    
  hosts: ubuntu                                                                                                                              
  tasks:  
    - name: apt module update
      apt:
        upgrade: yes
        update_cache: yes
    - name: install apache2                                                                                                                         
      apt: 
        name=apache2 state=latest                                                                                                                 
    -  name: start the apache2 service                                                                                                                    
       service:                                                                                                                                    
         name: apache2                                                                                                                               
         state: started  